export const ADD_TO_CART ="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const EMPTY_CART="EMPTY_CART";
export const BOOK_LIST ="BOOK_LIST";
export const SET_BOOK_LIST="SET_BOOK_LIST";
export const SEARCH_BOOK="SEARCH_BOOK";
export const SEARCH_BOOK_BY_CATEGORY="SEARCH_BOOK_BY_CATEGORY";
export const LOADING="LOADING";
export const LOADED="LOADED";
